/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package iteration1;

import java.io.IOException;

/**
 *
 * @author Ayush Kumar [Student number: 2028016]
 * 
 * This is the Source Code for the Supermarket application: BruMarket. BruMarket is 
 * a management software for supermarkets where the employee/manager can add, order, 
 * update and view the products to keep track of the stock and manage the logistic
 * aspects.
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        initComponents();
        
        Customer = new Customer();
        Employee = new Employee();
        ProductList = new ProductList();
        
        jTabInMemory1 = jMainTabbedPane.getComponentAt(1);
        jTabInMemory2 = jMainTabbedPane.getComponentAt(2);
        jTabInMemory3 = jMainTabbedPane.getComponentAt(3);
        jTabInMemory4 = jMainTabbedPane.getComponentAt(4);
        jTabInMemory5 = jMainTabbedPane.getComponentAt(5);

        jMainTabbedPane.remove(1);
        jMainTabbedPane.remove(1);
        jMainTabbedPane.remove(1);
        jMainTabbedPane.remove(1);
        jMainTabbedPane.remove(1);     

        for (int index = 0; index < jMainTabbedPane.getTabCount(); index++)
        {
            if (!jMainTabbedPane.getTitleAt(index).contentEquals("Login"))
                jMainTabbedPane.setEnabledAt(index,false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jStatusPanel = new javax.swing.JPanel();
        jProgressCompletionBar = new javax.swing.JProgressBar();
        jStatusMessageLabel = new javax.swing.JLabel();
        jMainTabbedPane = new javax.swing.JTabbedPane();
        jLoginPanel = new javax.swing.JPanel();
        jLOGINLabel = new javax.swing.JLabel();
        jLoginInstructionLabel = new javax.swing.JLabel();
        jUserIDLabel = new javax.swing.JLabel();
        jUserIDTextField = new javax.swing.JTextField();
        jPasswordLabel = new javax.swing.JLabel();
        jPasswordTextField = new javax.swing.JTextField();
        jRegisterButton = new javax.swing.JButton();
        jLoginButton = new javax.swing.JButton();
        jRegisterPanel = new javax.swing.JPanel();
        jREGISTEREMPLOYEELabel = new javax.swing.JLabel();
        jEmployeeUserIDLabel = new javax.swing.JLabel();
        jEmployeeUserIDTextField = new javax.swing.JTextField();
        jEmployeePasswordLabel = new javax.swing.JLabel();
        jEmployeePasswordTextField = new javax.swing.JTextField();
        jRegisterEmployeeButton = new javax.swing.JButton();
        jEmployeeInstructionLabel = new javax.swing.JLabel();
        jReOrderProductPanel = new javax.swing.JPanel();
        jReOrderInstructionLabel = new javax.swing.JLabel();
        jReOrderProductLabel = new javax.swing.JLabel();
        jReOrderProductComboBox = new javax.swing.JComboBox<>();
        jReOrderProductNameLabel = new javax.swing.JLabel();
        jReOrderProductNameTextField = new javax.swing.JTextField();
        jReOrderVendorLabel = new javax.swing.JLabel();
        jReOrderVendorComboBox = new javax.swing.JComboBox<>();
        jSearchProductButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jSearchProductTextArea = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        jOrderProductTextArea = new javax.swing.JTextArea();
        jDeliveryChargeLabel = new javax.swing.JLabel();
        jDynamicDeliveryChargeLabel = new javax.swing.JLabel();
        jRecommendedAmountLabel = new javax.swing.JLabel();
        jDynamicRecommendedAmountLabel = new javax.swing.JLabel();
        jReOrderAmountLabel = new javax.swing.JLabel();
        jReOrderAmountTextField = new javax.swing.JTextField();
        jReOrderButton = new javax.swing.JButton();
        jReOrderImageLabel = new javax.swing.JLabel();
        jProductListPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jProductListTextArea = new javax.swing.JTextArea();
        jProductListInstrsuctionLabel = new javax.swing.JLabel();
        jUpdateProductPanel = new javax.swing.JPanel();
        jUpdateProductInstructionLabel = new javax.swing.JLabel();
        jUpdateProductSelectProductLabel = new javax.swing.JLabel();
        jUpdateProductProductNameLabel = new javax.swing.JLabel();
        jUpdateProductQuantityLabel = new javax.swing.JLabel();
        jUpdateProductDateOfOrderLabel = new javax.swing.JLabel();
        jUpdateProductComboBox = new javax.swing.JComboBox<>();
        jUpdateProductProductNameTextField = new javax.swing.JTextField();
        jUpdateProductQuantityTextField = new javax.swing.JTextField();
        jUpdateProductDateOfOrderTextField = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        jUpdatedProductTextArea = new javax.swing.JTextArea();
        jUpdateProductButton = new javax.swing.JButton();
        jNewProductPanel = new javax.swing.JPanel();
        jNewProductInstructionLabel = new javax.swing.JLabel();
        jSelectProductLabel = new javax.swing.JLabel();
        jSelectProductComboBox = new javax.swing.JComboBox<>();
        jProductNameLabel = new javax.swing.JLabel();
        jProductNameTextField = new javax.swing.JTextField();
        jProductWeightLabel = new javax.swing.JLabel();
        jProductWeightTextField = new javax.swing.JTextField();
        jNoVATPriceLabel = new javax.swing.JLabel();
        jNoVATPriceTextField = new javax.swing.JTextField();
        jExpiryDateLabel = new javax.swing.JLabel();
        jExpiryDateTextField = new javax.swing.JTextField();
        jVendorLabel = new javax.swing.JLabel();
        jVendorComboBox = new javax.swing.JComboBox<>();
        jDateToOrderLabel = new javax.swing.JLabel();
        jDateToOrderTextField = new javax.swing.JTextField();
        jStockLabel = new javax.swing.JLabel();
        jStockTextField = new javax.swing.JTextField();
        jMinQuantityLabel = new javax.swing.JLabel();
        jMaxQuantityLabel = new javax.swing.JLabel();
        jMinQuantityTextField = new javax.swing.JTextField();
        jMaxQuantityTextField = new javax.swing.JTextField();
        jSaveProductButton = new javax.swing.JButton();
        jEditVATLabel = new javax.swing.JLabel();
        jEditVATTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jNewProductTextArea = new javax.swing.JTextArea();
        jSaveVATButton = new javax.swing.JButton();
        jImageLabel = new javax.swing.JLabel();
        jProductImageLabel = new javax.swing.JLabel();
        jImagePathTextField = new javax.swing.JTextField();
        jMenuBar = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jProgressCompletionBar.setForeground(new java.awt.Color(51, 98, 140));

        jStatusMessageLabel.setFont(new java.awt.Font("Helvetica Neue", 2, 13)); // NOI18N
        jStatusMessageLabel.setForeground(new java.awt.Color(51, 98, 140));
        jStatusMessageLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jStatusMessageLabel.setText("The supermarket application is running...");

        javax.swing.GroupLayout jStatusPanelLayout = new javax.swing.GroupLayout(jStatusPanel);
        jStatusPanel.setLayout(jStatusPanelLayout);
        jStatusPanelLayout.setHorizontalGroup(
            jStatusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jStatusPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jStatusMessageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jProgressCompletionBar, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jStatusPanelLayout.setVerticalGroup(
            jStatusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jStatusPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jStatusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jStatusPanelLayout.createSequentialGroup()
                        .addComponent(jStatusMessageLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jProgressCompletionBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jLOGINLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLOGINLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLOGINLabel.setText("LOGIN");

        jLoginInstructionLabel.setFont(new java.awt.Font("Helvetica Neue", 2, 13)); // NOI18N
        jLoginInstructionLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLoginInstructionLabel.setText("Welcome to BruMarket! Please enter your credentials");

        jUserIDLabel.setText("User ID");

        jPasswordLabel.setText("Password");

        jRegisterButton.setBackground(new java.awt.Color(51, 98, 140));
        jRegisterButton.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jRegisterButton.setForeground(new java.awt.Color(255, 255, 255));
        jRegisterButton.setText("Register");
        jRegisterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRegisterButtonActionPerformed(evt);
            }
        });

        jLoginButton.setBackground(new java.awt.Color(51, 98, 140));
        jLoginButton.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLoginButton.setForeground(new java.awt.Color(255, 255, 255));
        jLoginButton.setText("Login");
        jLoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLoginButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jLoginPanelLayout = new javax.swing.GroupLayout(jLoginPanel);
        jLoginPanel.setLayout(jLoginPanelLayout);
        jLoginPanelLayout.setHorizontalGroup(
            jLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLoginPanelLayout.createSequentialGroup()
                .addContainerGap(237, Short.MAX_VALUE)
                .addGroup(jLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLoginPanelLayout.createSequentialGroup()
                        .addComponent(jUserIDLabel)
                        .addGap(402, 402, 402))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLoginPanelLayout.createSequentialGroup()
                        .addGroup(jLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPasswordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jUserIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(345, 345, 345))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLoginPanelLayout.createSequentialGroup()
                        .addComponent(jPasswordLabel)
                        .addGap(397, 397, 397))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLoginPanelLayout.createSequentialGroup()
                        .addComponent(jLOGINLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(369, 369, 369))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLoginPanelLayout.createSequentialGroup()
                        .addComponent(jRegisterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(169, 169, 169)
                        .addComponent(jLoginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(243, 243, 243))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLoginPanelLayout.createSequentialGroup()
                        .addComponent(jLoginInstructionLabel)
                        .addGap(261, 261, 261))))
        );
        jLoginPanelLayout.setVerticalGroup(
            jLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLoginPanelLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jLOGINLabel)
                .addGap(18, 18, 18)
                .addComponent(jLoginInstructionLabel)
                .addGap(23, 23, 23)
                .addComponent(jUserIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(jUserIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPasswordLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPasswordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRegisterButton)
                    .addComponent(jLoginButton))
                .addContainerGap(183, Short.MAX_VALUE))
        );

        jMainTabbedPane.addTab("Login", jLoginPanel);

        jREGISTEREMPLOYEELabel.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jREGISTEREMPLOYEELabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jREGISTEREMPLOYEELabel.setText("REGISTER EMPLOYEE");

        jEmployeeUserIDLabel.setText("User ID");

        jEmployeePasswordLabel.setText("Password");

        jRegisterEmployeeButton.setBackground(new java.awt.Color(51, 98, 140));
        jRegisterEmployeeButton.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jRegisterEmployeeButton.setForeground(new java.awt.Color(255, 255, 255));
        jRegisterEmployeeButton.setText("Register");
        jRegisterEmployeeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRegisterEmployeeButtonActionPerformed(evt);
            }
        });

        jEmployeeInstructionLabel.setFont(new java.awt.Font("Helvetica Neue", 2, 13)); // NOI18N
        jEmployeeInstructionLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jEmployeeInstructionLabel.setText("Please register the employee with new credentials here!");

        javax.swing.GroupLayout jRegisterPanelLayout = new javax.swing.GroupLayout(jRegisterPanel);
        jRegisterPanel.setLayout(jRegisterPanelLayout);
        jRegisterPanelLayout.setHorizontalGroup(
            jRegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jRegisterPanelLayout.createSequentialGroup()
                .addGap(256, 256, 256)
                .addGroup(jRegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jRegisterPanelLayout.createSequentialGroup()
                        .addComponent(jREGISTEREMPLOYEELabel)
                        .addGap(61, 61, 61))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jRegisterPanelLayout.createSequentialGroup()
                        .addComponent(jEmployeePasswordLabel)
                        .addGap(136, 136, 136))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jRegisterPanelLayout.createSequentialGroup()
                        .addGroup(jRegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jEmployeePasswordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jEmployeeUserIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jRegisterPanelLayout.createSequentialGroup()
                                .addComponent(jRegisterEmployeeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)))
                        .addGap(84, 84, 84))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jRegisterPanelLayout.createSequentialGroup()
                        .addComponent(jEmployeeUserIDLabel)
                        .addGap(141, 141, 141))
                    .addComponent(jEmployeeInstructionLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(273, Short.MAX_VALUE))
        );
        jRegisterPanelLayout.setVerticalGroup(
            jRegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jRegisterPanelLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(jREGISTEREMPLOYEELabel)
                .addGap(18, 18, 18)
                .addComponent(jEmployeeInstructionLabel)
                .addGap(18, 18, 18)
                .addComponent(jEmployeeUserIDLabel)
                .addGap(22, 22, 22)
                .addComponent(jEmployeeUserIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jEmployeePasswordLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jEmployeePasswordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jRegisterEmployeeButton)
                .addContainerGap(163, Short.MAX_VALUE))
        );

        jMainTabbedPane.addTab("Register", jRegisterPanel);

        jReOrderInstructionLabel.setFont(new java.awt.Font("Helvetica Neue", 2, 13)); // NOI18N
        jReOrderInstructionLabel.setText("Re-order products from vendor here");

        jReOrderProductLabel.setText("Select Product");

        jReOrderProductComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fruits", "Vegetables", "Poultry", "Fish", "Dairy", "Sweets" }));

        jReOrderProductNameLabel.setText("Product Name");

        jReOrderVendorLabel.setText("Vendor");

        jReOrderVendorComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gardenia", "Billy The Butcher", "Dairy Queen", "SweetStop" }));

        jSearchProductButton.setBackground(new java.awt.Color(51, 98, 140));
        jSearchProductButton.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jSearchProductButton.setForeground(new java.awt.Color(255, 255, 255));
        jSearchProductButton.setText("Search");
        jSearchProductButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSearchProductButtonActionPerformed(evt);
            }
        });

        jSearchProductTextArea.setColumns(20);
        jSearchProductTextArea.setRows(5);
        jScrollPane3.setViewportView(jSearchProductTextArea);

        jOrderProductTextArea.setColumns(20);
        jOrderProductTextArea.setRows(5);
        jScrollPane4.setViewportView(jOrderProductTextArea);

        jDeliveryChargeLabel.setText("Delivery Charge");

        jDynamicDeliveryChargeLabel.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        jDynamicDeliveryChargeLabel.setForeground(new java.awt.Color(0, 204, 0));
        jDynamicDeliveryChargeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jDynamicDeliveryChargeLabel.setText("[Charge]");

        jRecommendedAmountLabel.setText("Recommended Amount");

        jDynamicRecommendedAmountLabel.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        jDynamicRecommendedAmountLabel.setForeground(new java.awt.Color(0, 204, 0));
        jDynamicRecommendedAmountLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jDynamicRecommendedAmountLabel.setText("[Amount]");

        jReOrderAmountLabel.setText("Amount to Re-order");

        jReOrderButton.setBackground(new java.awt.Color(51, 98, 140));
        jReOrderButton.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jReOrderButton.setForeground(new java.awt.Color(255, 255, 255));
        jReOrderButton.setText("Order");
        jReOrderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jReOrderButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jReOrderProductPanelLayout = new javax.swing.GroupLayout(jReOrderProductPanel);
        jReOrderProductPanel.setLayout(jReOrderProductPanelLayout);
        jReOrderProductPanelLayout.setHorizontalGroup(
            jReOrderProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jReOrderProductPanelLayout.createSequentialGroup()
                .addGroup(jReOrderProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jReOrderProductPanelLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jReOrderProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jReOrderProductLabel)
                            .addComponent(jReOrderProductNameLabel)
                            .addComponent(jReOrderVendorLabel)
                            .addComponent(jDeliveryChargeLabel)
                            .addComponent(jRecommendedAmountLabel)
                            .addComponent(jReOrderAmountLabel))
                        .addGroup(jReOrderProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jReOrderProductPanelLayout.createSequentialGroup()
                                .addGap(109, 109, 109)
                                .addGroup(jReOrderProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jDynamicRecommendedAmountLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jDynamicDeliveryChargeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(77, 77, 77))
                            .addGroup(jReOrderProductPanelLayout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addGroup(jReOrderProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jReOrderProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jReOrderProductComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jReOrderProductNameTextField)
                                        .addComponent(jReOrderVendorComboBox, 0, 170, Short.MAX_VALUE))
                                    .addComponent(jReOrderAmountTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18))))
                    .addGroup(jReOrderProductPanelLayout.createSequentialGroup()
                        .addGroup(jReOrderProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jReOrderProductPanelLayout.createSequentialGroup()
                                .addGap(110, 110, 110)
                                .addComponent(jSearchProductButton, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jReOrderProductPanelLayout.createSequentialGroup()
                                .addGap(106, 106, 106)
                                .addComponent(jReOrderButton, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jReOrderProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 440, Short.MAX_VALUE)
                    .addGroup(jReOrderProductPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jReOrderImageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jReOrderProductPanelLayout.createSequentialGroup()
                .addGap(280, 280, 280)
                .addComponent(jReOrderInstructionLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jReOrderProductPanelLayout.setVerticalGroup(
            jReOrderProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jReOrderProductPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jReOrderInstructionLabel)
                .addGap(34, 34, 34)
                .addGroup(jReOrderProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jReOrderImageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jReOrderProductPanelLayout.createSequentialGroup()
                        .addGroup(jReOrderProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jReOrderProductLabel)
                            .addComponent(jReOrderProductComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jReOrderProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jReOrderProductNameLabel)
                            .addComponent(jReOrderProductNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jReOrderProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jReOrderVendorLabel)
                            .addComponent(jReOrderVendorComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addComponent(jSearchProductButton))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jReOrderProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jReOrderProductPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jReOrderProductPanelLayout.createSequentialGroup()
                        .addGroup(jReOrderProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jDeliveryChargeLabel)
                            .addComponent(jDynamicDeliveryChargeLabel))
                        .addGap(18, 18, 18)
                        .addGroup(jReOrderProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRecommendedAmountLabel)
                            .addComponent(jDynamicRecommendedAmountLabel))
                        .addGap(18, 18, 18)
                        .addGroup(jReOrderProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jReOrderAmountLabel)
                            .addComponent(jReOrderAmountTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jReOrderButton)
                        .addGap(25, 25, 25))))
        );

        jMainTabbedPane.addTab("Re-order Product", jReOrderProductPanel);

        jProductListTextArea.setColumns(20);
        jProductListTextArea.setRows(5);
        jProductListTextArea.setText("Fruit, Mango, 5.0, 3.25, 3.35, 12/12/2022, 15/12/2022, 30.0, 15.0, 100.0, C:\\Users\\SLL700\\OneDrive - Brunel University London\\Desktop\\Uni\\EE2606 Object Oriented Systems and Programming\\Iteration1\\Mango.jpeg, Gardenia, Address_Gardenia, 19.99, 14\nVegetables, Courgettes, 10.0, 4.75, 4.77, 15/12/2022, 20/12/2022, 30.0, 15.0, 75.0, C:\\Users\\SLL700\\OneDrive - Brunel University London\\Desktop\\Uni\\EE2606 Object Oriented Systems and Programming\\Iteration1\\Courgette.jpeg, Gardenia, Address_Gardenia, 19.99, 14\nPoultry, Chicken, 20.0, 5.99. 6.0, 13/12/2022, 17/12/2022, 40.0, 20.0, 80.0, C:\\Users\\SLL700\\OneDrive - Brunel University London\\Desktop\\Uni\\EE2606 Object Oriented Systems and Programming\\Iteration1\\Chicken.jpg, Billy The Butcher, Address_BillyTheButcher, 29.99, 7\nFish, Cod, 25.0, 7.95, 8.0, 15/12/2022, 20/12/2022, 35.0, 25.0, 90.0, C:\\Users\\SLL700\\OneDrive - Brunel University London\\Desktop\\Uni\\EE2606 Object Oriented Systems and Programming\\Iteration1\\Cod.jpeg, Billy The Butcher, Address_BillyTheButcher, 29.99, 7\nDairy, Milk, 20.0, 12.99, 13.0, 13/12/2022, 15/12/2022, 15.0, 10.0, 25.0, C:\\Users\\SLL700\\OneDrive - Brunel University London\\Desktop\\Uni\\EE2606 Object Oriented Systems and Programming\\Iteration1\\Milk.jpeg, Dairy Queen, Address_DairyQueen, 8.99, 1\nSweets, Chocolate, 10.0, 2.99, 3.19, 20/01/2023, 25/01/2022, 25.0, 15.0, 50.0, C:\\Users\\SLL700\\OneDrive - Brunel University London\\Desktop\\Uni\\EE2606 Object Oriented Systems and Programming\\Iteration1\\Chocolate.jpeg, SweetStop, Address_SweetStop, 39.99, 5\nVegetables, Broccoli, 10.0, 2.75. 2.77, 15/12/2022, 17/12/2022, 35.0, 20.0, 75.0, C:\\Users\\SLL700\\OneDrive - Brunel University London\\Desktop\\Uni\\EE2606 Object Oriented Systems and Programming\\Iteration1\\Broccoli.jpg, Gardenia, Address_Gardenia, 19.99, 14");
        jScrollPane2.setViewportView(jProductListTextArea);

        jProductListInstrsuctionLabel.setFont(new java.awt.Font("Arial", 2, 13)); // NOI18N
        jProductListInstrsuctionLabel.setText("View the list of products here");

        javax.swing.GroupLayout jProductListPanelLayout = new javax.swing.GroupLayout(jProductListPanel);
        jProductListPanel.setLayout(jProductListPanelLayout);
        jProductListPanelLayout.setHorizontalGroup(
            jProductListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jProductListPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 837, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jProductListPanelLayout.createSequentialGroup()
                .addGap(320, 320, 320)
                .addComponent(jProductListInstrsuctionLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jProductListPanelLayout.setVerticalGroup(
            jProductListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jProductListPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jProductListInstrsuctionLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 453, Short.MAX_VALUE))
        );

        jMainTabbedPane.addTab("Product List", jProductListPanel);

        jUpdateProductInstructionLabel.setFont(new java.awt.Font("Arial", 2, 13)); // NOI18N
        jUpdateProductInstructionLabel.setText("Please update product infromation here");

        jUpdateProductSelectProductLabel.setText("Select Product");

        jUpdateProductProductNameLabel.setText("Product Name");

        jUpdateProductQuantityLabel.setText("Enter Quantity");

        jUpdateProductDateOfOrderLabel.setText("Last date of Order");

        jUpdateProductComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fruits", "Vegetables", "Poultry", "Fish", "Dairy", "Sweets" }));

        jUpdatedProductTextArea.setColumns(20);
        jUpdatedProductTextArea.setRows(5);
        jScrollPane5.setViewportView(jUpdatedProductTextArea);

        jUpdateProductButton.setBackground(new java.awt.Color(51, 98, 140));
        jUpdateProductButton.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jUpdateProductButton.setForeground(new java.awt.Color(255, 255, 255));
        jUpdateProductButton.setText("Update");
        jUpdateProductButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jUpdateProductButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jUpdateProductPanelLayout = new javax.swing.GroupLayout(jUpdateProductPanel);
        jUpdateProductPanel.setLayout(jUpdateProductPanelLayout);
        jUpdateProductPanelLayout.setHorizontalGroup(
            jUpdateProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jUpdateProductPanelLayout.createSequentialGroup()
                .addGap(254, 254, 254)
                .addGroup(jUpdateProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jUpdateProductSelectProductLabel)
                    .addComponent(jUpdateProductProductNameLabel)
                    .addComponent(jUpdateProductQuantityLabel)
                    .addComponent(jUpdateProductDateOfOrderLabel))
                .addGap(48, 48, 48)
                .addGroup(jUpdateProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jUpdateProductComboBox, 0, 170, Short.MAX_VALUE)
                    .addComponent(jUpdateProductProductNameTextField)
                    .addComponent(jUpdateProductQuantityTextField)
                    .addComponent(jUpdateProductDateOfOrderTextField))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jUpdateProductPanelLayout.createSequentialGroup()
                .addContainerGap(340, Short.MAX_VALUE)
                .addComponent(jUpdateProductInstructionLabel)
                .addGap(282, 282, 282))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jUpdateProductPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5)
                .addContainerGap())
            .addGroup(jUpdateProductPanelLayout.createSequentialGroup()
                .addGap(314, 314, 314)
                .addComponent(jUpdateProductButton, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jUpdateProductPanelLayout.setVerticalGroup(
            jUpdateProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jUpdateProductPanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jUpdateProductInstructionLabel)
                .addGap(18, 18, 18)
                .addGroup(jUpdateProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jUpdateProductSelectProductLabel)
                    .addComponent(jUpdateProductComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jUpdateProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jUpdateProductProductNameLabel)
                    .addComponent(jUpdateProductProductNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jUpdateProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jUpdateProductQuantityLabel)
                    .addComponent(jUpdateProductQuantityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jUpdateProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jUpdateProductDateOfOrderLabel)
                    .addComponent(jUpdateProductDateOfOrderTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jUpdateProductButton)
                .addContainerGap())
        );

        jMainTabbedPane.addTab("Update Product", jUpdateProductPanel);

        jNewProductInstructionLabel.setFont(new java.awt.Font("Helvetica Neue", 2, 13)); // NOI18N
        jNewProductInstructionLabel.setText("Please enter new product and its information here");

        jSelectProductLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jSelectProductLabel.setText("Select Product");

        jSelectProductComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fruits", "Vegetables", "Poultry", "Fish", "Dairy", "Sweets" }));

        jProductNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jProductNameLabel.setText("Product Name");

        jProductWeightLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jProductWeightLabel.setText("Product Weight");

        jNoVATPriceLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jNoVATPriceLabel.setText("VAT Exclusive Price");

        jExpiryDateLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jExpiryDateLabel.setText("Expiry Date");

        jVendorLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jVendorLabel.setText("Vendor");

        jVendorComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gardenia", "Billy The Butcher", "Dairy Queen", "SweetStop" }));

        jDateToOrderLabel.setText("Estimated Date to Order");

        jStockLabel.setText("Enter Stock");

        jMinQuantityLabel.setText("Enter Minimum Quantity");

        jMaxQuantityLabel.setText("Enter Maximum Quantity");

        jSaveProductButton.setBackground(new java.awt.Color(51, 98, 140));
        jSaveProductButton.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jSaveProductButton.setForeground(new java.awt.Color(255, 255, 255));
        jSaveProductButton.setText("Save");
        jSaveProductButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSaveProductButtonActionPerformed(evt);
            }
        });

        jEditVATLabel.setText("Edit VAT");

        jNewProductTextArea.setColumns(20);
        jNewProductTextArea.setRows(5);
        jScrollPane1.setViewportView(jNewProductTextArea);

        jSaveVATButton.setBackground(new java.awt.Color(51, 98, 140));
        jSaveVATButton.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jSaveVATButton.setForeground(new java.awt.Color(255, 255, 255));
        jSaveVATButton.setText("Save VAT");
        jSaveVATButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSaveVATButtonActionPerformed(evt);
            }
        });

        jProductImageLabel.setText("Enter Image Path");

        javax.swing.GroupLayout jNewProductPanelLayout = new javax.swing.GroupLayout(jNewProductPanel);
        jNewProductPanel.setLayout(jNewProductPanelLayout);
        jNewProductPanelLayout.setHorizontalGroup(
            jNewProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jNewProductPanelLayout.createSequentialGroup()
                .addGroup(jNewProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jNewProductPanelLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jNewProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSelectProductLabel)
                            .addComponent(jProductNameLabel)
                            .addComponent(jProductWeightLabel)
                            .addComponent(jNoVATPriceLabel)
                            .addComponent(jExpiryDateLabel))
                        .addGap(32, 32, 32)
                        .addGroup(jNewProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jProductWeightTextField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jProductNameTextField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSelectProductComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, 170, Short.MAX_VALUE)
                            .addComponent(jNoVATPriceTextField)
                            .addComponent(jExpiryDateTextField, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jNewProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jNewProductPanelLayout.createSequentialGroup()
                                .addComponent(jVendorLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jVendorComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jNewProductPanelLayout.createSequentialGroup()
                                .addGroup(jNewProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jDateToOrderLabel)
                                    .addComponent(jStockLabel)
                                    .addComponent(jMinQuantityLabel)
                                    .addComponent(jMaxQuantityLabel)
                                    .addComponent(jProductImageLabel))
                                .addGap(59, 59, 59)
                                .addGroup(jNewProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jDateToOrderTextField)
                                    .addComponent(jStockTextField)
                                    .addComponent(jMinQuantityTextField)
                                    .addComponent(jMaxQuantityTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)))))
                    .addGroup(jNewProductPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jImageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jNewProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jNewProductPanelLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jNewProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSaveProductButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jNewProductPanelLayout.createSequentialGroup()
                                        .addComponent(jEditVATLabel)
                                        .addGap(33, 33, 33)
                                        .addComponent(jEditVATTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addComponent(jSaveVATButton))
                            .addGroup(jNewProductPanelLayout.createSequentialGroup()
                                .addGap(269, 269, 269)
                                .addComponent(jImagePathTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE))))
                    .addGroup(jNewProductPanelLayout.createSequentialGroup()
                        .addGap(273, 273, 273)
                        .addComponent(jNewProductInstructionLabel)))
                .addGap(20, 20, 20))
        );
        jNewProductPanelLayout.setVerticalGroup(
            jNewProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jNewProductPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jNewProductInstructionLabel)
                .addGap(30, 30, 30)
                .addGroup(jNewProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSelectProductLabel)
                    .addComponent(jSelectProductComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jVendorComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jVendorLabel))
                .addGap(18, 18, 18)
                .addGroup(jNewProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jNewProductPanelLayout.createSequentialGroup()
                        .addGroup(jNewProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jProductNameLabel)
                            .addComponent(jProductNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jNewProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jProductWeightLabel)
                            .addComponent(jProductWeightTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jNewProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jNoVATPriceLabel)
                            .addComponent(jNoVATPriceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jNewProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jExpiryDateLabel)
                            .addComponent(jExpiryDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jNewProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                            .addComponent(jImageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(jNewProductPanelLayout.createSequentialGroup()
                        .addGroup(jNewProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jDateToOrderLabel)
                            .addComponent(jDateToOrderTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jNewProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jStockLabel)
                            .addComponent(jStockTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jNewProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jMinQuantityLabel)
                            .addComponent(jMinQuantityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jNewProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jMaxQuantityLabel)
                            .addComponent(jMaxQuantityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jNewProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jImagePathTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jProductImageLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                        .addGroup(jNewProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jEditVATLabel)
                            .addComponent(jEditVATTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSaveVATButton))
                        .addGap(39, 39, 39)
                        .addComponent(jSaveProductButton)
                        .addGap(64, 64, 64))))
        );

        jMainTabbedPane.addTab("New Product", jNewProductPanel);

        jMenu1.setText("File");
        jMenuBar.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar.add(jMenu2);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jStatusPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jMainTabbedPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jMainTabbedPane)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jStatusPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRegisterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRegisterButtonActionPerformed
        // This uses key-login for activating the software in order to register an employee:
        if(jUserIDTextField.getText().contentEquals("Roxy")
                && jPasswordTextField.getText().contentEquals("2308")){
            
            jMainTabbedPane.addTab("Register Employee", jTabInMemory1);
            jMainTabbedPane.setSelectedIndex(1);
        }else{
            if(!Customer.IsRegistered(jUserIDTextField.getText(), jPasswordTextField.getText()))
                jStatusMessageLabel.setText("The system can not register as the field is wrong.");
            else
                jStatusMessageLabel.setText(jUserIDTextField.getText() + " has succesfully been registered as a User!");
        }
        
    }//GEN-LAST:event_jRegisterButtonActionPerformed

    private void jLoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLoginButtonActionPerformed
        // This is user login system where a pair of pre-entered data is used to access BruMarket:
        if(Employee.IsEmployee(jUserIDTextField.getText(), jPasswordTextField.getText(), "EmployeeLoginFile.txt")){
            jStatusMessageLabel.setText("Employee " + jUserIDTextField.getText() + " is logged in..."); // Prompts login success
            jMainTabbedPane.addTab("New Product", jTabInMemory5); // Tab manipulation
            jMainTabbedPane.addTab("Re-Order Product", jTabInMemory2);
            jMainTabbedPane.addTab("Product List", jTabInMemory3);
            jMainTabbedPane.addTab("Update Product", jTabInMemory4);
            jMainTabbedPane.setSelectedIndex(1);
            
            if(ProductList.SetReOrder()){
                jStatusMessageLabel.setText("Product: " + ProductList.GetName() + " needs to be Re-Ordered!");
            }
        }else{
            if(Customer.IsCustomer(jUserIDTextField.getText(), jPasswordTextField.getText(), "CustomerLoginFile.txt")){
                jStatusMessageLabel.setText("Customer " + jUserIDTextField.getText() + " is logged in...");
            }else{
                jStatusMessageLabel.setText("Error logging in!");
            }
        }
    }//GEN-LAST:event_jLoginButtonActionPerformed

    private void jRegisterEmployeeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRegisterEmployeeButtonActionPerformed
        // The employee is registred here and saved into the file:
        if(!Employee.IsRegistered(jEmployeeUserIDTextField.getText(), jEmployeePasswordTextField.getText()))
            jStatusMessageLabel.setText("Error while registering the Employee!");
        else{
            jStatusMessageLabel.setText("Employee " + jEmployeeUserIDTextField.getText() + " is registered.");
            
            jMainTabbedPane.addTab("New Product",jTabInMemory5);
            jMainTabbedPane.addTab("Re-Order Product",jTabInMemory2);
            jMainTabbedPane.addTab("Product List",jTabInMemory3);
            jMainTabbedPane.addTab("Update Product",jTabInMemory4);
            jMainTabbedPane.setSelectedIndex(1);
        }
    }//GEN-LAST:event_jRegisterEmployeeButtonActionPerformed

    private void jSearchProductButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSearchProductButtonActionPerformed
        // This accesses the backend to search for a prompted product:
        if(!ProductList.ReOrderProduct(jReOrderProductComboBox.getSelectedItem().toString(),
                jReOrderProductNameTextField.getText(), jReOrderVendorComboBox.getSelectedItem().toString()))
            jStatusMessageLabel.setText("Product " + jProductNameTextField.getText() + " not found!");
        else{
            ProductList.DisplayProduct(jReOrderProductComboBox.getSelectedItem().toString(),
                    jReOrderProductNameTextField.getText(), jSearchProductTextArea);
            
            jDynamicDeliveryChargeLabel.setText(String.valueOf(ProductList.GetCharges()));
            jDynamicRecommendedAmountLabel.setText(String.valueOf(ProductList.GetRecommendedAmount()));      
        
        try {
              ProductList.DisplayImage(jReOrderImageLabel);
            } catch (IOException ex) {}
        }
    }//GEN-LAST:event_jSearchProductButtonActionPerformed

    private void jReOrderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jReOrderButtonActionPerformed
        // This allows a user to re-order a product:
        ProductList.SaveReOrderToFile(Double.valueOf(jReOrderAmountTextField.getText()));
        ProductList.DisplayReOrder(jReOrderProductComboBox.getSelectedItem().toString(),
                jReOrderProductNameTextField.getText(), Double.valueOf(jReOrderAmountTextField.getText()), jOrderProductTextArea);
        jStatusMessageLabel.setText("Reorder of "+ jReOrderProductNameTextField.getText()+" was successful.");
    }//GEN-LAST:event_jReOrderButtonActionPerformed

    private void jUpdateProductButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jUpdateProductButtonActionPerformed
         // User can update the product list here:
        ProductList.UpdateProduct(jUpdateProductComboBox.getSelectedItem().toString(),
               jUpdateProductProductNameTextField.getText(),Double.valueOf(jUpdateProductQuantityTextField.getText()),
               jUpdateProductDateOfOrderTextField.getText());
        jStatusMessageLabel.setText("Product " + jUpdateProductProductNameTextField.getText() + " has been updated!");
        ProductList.DisplayProduct(jUpdateProductComboBox.getSelectedItem().toString(),
                jUpdateProductProductNameTextField.getText(), jUpdatedProductTextArea);
    }//GEN-LAST:event_jUpdateProductButtonActionPerformed

    private void jSaveVATButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSaveVATButtonActionPerformed
        // This saved the product VAT when a new product is added:
       ProductList.UpdateVAT(jSelectProductComboBox.getSelectedItem().toString(), 
               jProductNameTextField.getText(), Integer.valueOf(jEditVATTextField.getText()));
       ProductList.DisplayProduct(jSelectProductComboBox.getSelectedItem().toString(),
               jProductNameTextField.getText(),jNewProductTextArea);
    }//GEN-LAST:event_jSaveVATButtonActionPerformed

    private void jSaveProductButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSaveProductButtonActionPerformed
        // This saves the product into the product list:
        ProductList.GetProduct(jSelectProductComboBox.getSelectedItem().toString(), 
                jProductNameTextField.getText(), Double.valueOf(jProductWeightTextField.getText()),
                Double.valueOf(jNoVATPriceTextField.getText()),Double.valueOf(jNoVATPriceTextField.getText()),
                jExpiryDateTextField.getText(), jDateToOrderTextField.getText(), 
                Double.valueOf(jStockTextField.getText()), Double.valueOf(jMinQuantityTextField.getText()), 
                Double.valueOf(jMaxQuantityTextField.getText()), 
                jImagePathTextField.getText(),
                jVendorComboBox.getSelectedItem().toString());
        
        ProductList.SaveToFile();
        ProductList.DisplayProduct(jSelectProductComboBox.getSelectedItem().toString(), jProductNameTextField.getText(),jNewProductTextArea);
        jStatusMessageLabel.setText("Product " + jProductNameTextField.getText() + " was saved.");
        try {
//          displays the image of the product in the jImageLabel
            ProductList.DisplayImage(jImageLabel);
        } catch (IOException ex) {}
    }//GEN-LAST:event_jSaveProductButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }
    
    // The following is the Decleration of the Objects:
    private Customer Customer;
    private Employee Employee;
    private ProductList ProductList;
    
    // The following is the Decleration of the tab manipulation:
    private java.awt.Component jTabInMemory1;
    private java.awt.Component jTabInMemory2;
    private java.awt.Component jTabInMemory3;
    private java.awt.Component jTabInMemory4;
    private java.awt.Component jTabInMemory5;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jDateToOrderLabel;
    private javax.swing.JTextField jDateToOrderTextField;
    private javax.swing.JLabel jDeliveryChargeLabel;
    private javax.swing.JLabel jDynamicDeliveryChargeLabel;
    private javax.swing.JLabel jDynamicRecommendedAmountLabel;
    private javax.swing.JLabel jEditVATLabel;
    private javax.swing.JTextField jEditVATTextField;
    private javax.swing.JLabel jEmployeeInstructionLabel;
    private javax.swing.JLabel jEmployeePasswordLabel;
    private javax.swing.JTextField jEmployeePasswordTextField;
    private javax.swing.JLabel jEmployeeUserIDLabel;
    private javax.swing.JTextField jEmployeeUserIDTextField;
    private javax.swing.JLabel jExpiryDateLabel;
    private javax.swing.JTextField jExpiryDateTextField;
    private javax.swing.JLabel jImageLabel;
    private javax.swing.JTextField jImagePathTextField;
    private javax.swing.JLabel jLOGINLabel;
    private javax.swing.JButton jLoginButton;
    private javax.swing.JLabel jLoginInstructionLabel;
    private javax.swing.JPanel jLoginPanel;
    private javax.swing.JTabbedPane jMainTabbedPane;
    private javax.swing.JLabel jMaxQuantityLabel;
    private javax.swing.JTextField jMaxQuantityTextField;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JLabel jMinQuantityLabel;
    private javax.swing.JTextField jMinQuantityTextField;
    private javax.swing.JLabel jNewProductInstructionLabel;
    private javax.swing.JPanel jNewProductPanel;
    private javax.swing.JTextArea jNewProductTextArea;
    private javax.swing.JLabel jNoVATPriceLabel;
    private javax.swing.JTextField jNoVATPriceTextField;
    private javax.swing.JTextArea jOrderProductTextArea;
    private javax.swing.JLabel jPasswordLabel;
    private javax.swing.JTextField jPasswordTextField;
    private javax.swing.JLabel jProductImageLabel;
    private javax.swing.JLabel jProductListInstrsuctionLabel;
    private javax.swing.JPanel jProductListPanel;
    private javax.swing.JTextArea jProductListTextArea;
    private javax.swing.JLabel jProductNameLabel;
    private javax.swing.JTextField jProductNameTextField;
    private javax.swing.JLabel jProductWeightLabel;
    private javax.swing.JTextField jProductWeightTextField;
    private javax.swing.JProgressBar jProgressCompletionBar;
    private javax.swing.JLabel jREGISTEREMPLOYEELabel;
    private javax.swing.JLabel jReOrderAmountLabel;
    private javax.swing.JTextField jReOrderAmountTextField;
    private javax.swing.JButton jReOrderButton;
    private javax.swing.JLabel jReOrderImageLabel;
    private javax.swing.JLabel jReOrderInstructionLabel;
    private javax.swing.JComboBox<String> jReOrderProductComboBox;
    private javax.swing.JLabel jReOrderProductLabel;
    private javax.swing.JLabel jReOrderProductNameLabel;
    private javax.swing.JTextField jReOrderProductNameTextField;
    private javax.swing.JPanel jReOrderProductPanel;
    private javax.swing.JComboBox<String> jReOrderVendorComboBox;
    private javax.swing.JLabel jReOrderVendorLabel;
    private javax.swing.JLabel jRecommendedAmountLabel;
    private javax.swing.JButton jRegisterButton;
    private javax.swing.JButton jRegisterEmployeeButton;
    private javax.swing.JPanel jRegisterPanel;
    private javax.swing.JButton jSaveProductButton;
    private javax.swing.JButton jSaveVATButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JButton jSearchProductButton;
    private javax.swing.JTextArea jSearchProductTextArea;
    private javax.swing.JComboBox<String> jSelectProductComboBox;
    private javax.swing.JLabel jSelectProductLabel;
    private javax.swing.JLabel jStatusMessageLabel;
    private javax.swing.JPanel jStatusPanel;
    private javax.swing.JLabel jStockLabel;
    private javax.swing.JTextField jStockTextField;
    private javax.swing.JButton jUpdateProductButton;
    private javax.swing.JComboBox<String> jUpdateProductComboBox;
    private javax.swing.JLabel jUpdateProductDateOfOrderLabel;
    private javax.swing.JTextField jUpdateProductDateOfOrderTextField;
    private javax.swing.JLabel jUpdateProductInstructionLabel;
    private javax.swing.JPanel jUpdateProductPanel;
    private javax.swing.JLabel jUpdateProductProductNameLabel;
    private javax.swing.JTextField jUpdateProductProductNameTextField;
    private javax.swing.JLabel jUpdateProductQuantityLabel;
    private javax.swing.JTextField jUpdateProductQuantityTextField;
    private javax.swing.JLabel jUpdateProductSelectProductLabel;
    private javax.swing.JTextArea jUpdatedProductTextArea;
    private javax.swing.JLabel jUserIDLabel;
    private javax.swing.JTextField jUserIDTextField;
    private javax.swing.JComboBox<String> jVendorComboBox;
    private javax.swing.JLabel jVendorLabel;
    // End of variables declaration//GEN-END:variables
}
